/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const input: string;
const inputLabel: string;
const inputErrors: string;

export {
	input,
	inputLabel,
	inputErrors
};

export default {
	input,
	inputLabel,
	inputErrors
};
