/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const registerForm: string;
const title: string;
const input: string;
const button: string;
const formErrors: string;

export {
	registerForm,
	title,
	input,
	button,
	formErrors
};

export default {
	registerForm,
	title,
	input,
	button,
	formErrors
};
