/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const priceCard: string;
const mainPrice: string;
const price: string;
const change: string;
const positive: string;
const negative: string;
const statsGrid: string;
const statItem: string;

export {
	priceCard,
	mainPrice,
	price,
	change,
	positive,
	negative,
	statsGrid,
	statItem
};

export default {
	priceCard,
	mainPrice,
	price,
	change,
	positive,
	negative,
	statsGrid,
	statItem
};
