/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const mainContainer: string;
const ordersContainer: string;

export {
	mainContainer,
	ordersContainer
};

export default {
	mainContainer,
	ordersContainer
};
