/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const toggleButton: string;
const isSecondSelectedd: string;

export {
	toggleButton,
	isSecondSelectedd
};

export default {
	toggleButton,
	isSecondSelectedd
};
