/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const tradingPage: string;

export {
	tradingPage
};

export default {
	tradingPage
};
