/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const navigation: string;
const menuButton: string;
const dropdown: string;
const link: string;
const open: string;

export {
	navigation,
	menuButton,
	dropdown,
	link,
	open
};

export default {
	navigation,
	menuButton,
	dropdown,
	link,
	open
};
