/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const loginForm: string;
const title: string;
const button: string;
const formErrors: string;

export {
	loginForm,
	title,
	button,
	formErrors
};

export default {
	loginForm,
	title,
	button,
	formErrors
};
