/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const cryptoPriceTracker: string;
const error: string;
const title: string;
const priceGrid: string;
const tradingHeader: string;

export {
	cryptoPriceTracker,
	error,
	title,
	priceGrid,
	tradingHeader
};

export default {
	cryptoPriceTracker,
	error,
	title,
	priceGrid,
	tradingHeader
};
