/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const title: string;
const subtitle: string;
const homeLink: string;

export {
	container,
	title,
	subtitle,
	homeLink
};

export default {
	container,
	title,
	subtitle,
	homeLink
};
