/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const imageBackground: string;
const homePage: string;
const info: string;
const title: string;
const link: string;

export {
	imageBackground,
	homePage,
	info,
	title,
	link
};

export default {
	imageBackground,
	homePage,
	info,
	title,
	link
};
