/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const pageFooter: string;
const footerText: string;

export {
	pageFooter,
	footerText
};

export default {
	pageFooter,
	footerText
};
