/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const profileContainer: string;
const profileInfoContainer: string;
const portfolioHoldingsContainer: string;
const orderInfoTable: string;
const holding: string;
const portfolioHoldingsTable: string;

export {
	profileContainer,
	profileInfoContainer,
	portfolioHoldingsContainer,
	orderInfoTable,
	holding,
	portfolioHoldingsTable
};

export default {
	profileContainer,
	profileInfoContainer,
	portfolioHoldingsContainer,
	orderInfoTable,
	holding,
	portfolioHoldingsTable
};
