/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const mainContainer: string;
const mainContainerWithOrders: string;
const pageContainer: string;
const ordersContainer: string;
const header: string;
const backButton: string;
const title: string;
const tradeForm: string;
const tradeFormButtons: string;
const buyButton: string;
const tradeFormInput: string;
const sellButton: string;
const errorMessage: string;
const symbolHoldingContainer: string;

export {
	mainContainer,
	mainContainerWithOrders,
	pageContainer,
	ordersContainer,
	header,
	backButton,
	title,
	tradeForm,
	tradeFormButtons,
	buyButton,
	tradeFormInput,
	sellButton,
	errorMessage,
	symbolHoldingContainer
};

export default {
	mainContainer,
	mainContainerWithOrders,
	pageContainer,
	ordersContainer,
	header,
	backButton,
	title,
	tradeForm,
	tradeFormButtons,
	buyButton,
	tradeFormInput,
	sellButton,
	errorMessage,
	symbolHoldingContainer
};
