/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const header: string;
const themeSelector: string;
const headerTitle: string;
const loggedInHeaderData: string;

export {
	header,
	themeSelector,
	headerTitle,
	loggedInHeaderData
};

export default {
	header,
	themeSelector,
	headerTitle,
	loggedInHeaderData
};
