/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const orderCard: string;
const orderInfoTable: string;
const buy: string;
const sell: string;

export {
	orderCard,
	orderInfoTable,
	buy,
	sell
};

export default {
	orderCard,
	orderInfoTable,
	buy,
	sell
};
