/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const spinnerContainer: string;
const spinner: string;
const spin: string;

export {
	spinnerContainer,
	spinner,
	spin
};

export default {
	spinnerContainer,
	spinner,
	spin
};
