/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const priceInfoTable: string;
const priceCard: string;
const priceInfo: string;
const change: string;
const positive: string;
const negative: string;
const bond: string;

export {
	priceInfoTable,
	priceCard,
	priceInfo,
	change,
	positive,
	negative,
	bond
};

export default {
	priceInfoTable,
	priceCard,
	priceInfo,
	change,
	positive,
	negative,
	bond
};
